use crate::models::AliasStore;
use anyhow::{Context, Result};
use std::path::PathBuf;

fn config_dir() -> Result<PathBuf> {
    let dir = dirs::config_dir()
        .context("Could not find config directory")?
        .join("aka");
    std::fs::create_dir_all(&dir)?;
    Ok(dir)
}

pub fn generate(store: &AliasStore) -> Result<()> {
    let dir = config_dir()?;
    let sh_path = dir.join("aliases.sh");
    generate_bash(store, &sh_path)?;
    println!("Generated: {}", sh_path.display());
    Ok(())
}

fn generate_bash(store: &AliasStore, path: &PathBuf) -> Result<()> {
    let mut lines = vec!["# Generated by aka — do not edit manually".to_string()];
    for (name, alias) in &store.aliases {
        let escaped = alias.command.replace('\'', "'\\''");
        lines.push(format!("alias {}='{}'", name, escaped));
    }
    std::fs::write(path, lines.join("\n") + "\n")?;
    Ok(())
}